name: go-test

on:
  push:
    tags:
      - '*'
    branches:
      - '{{cookiecutter.default_branch}}'
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: ['{{cookiecutter.go_version}}.x']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Go test
        run: make go-test-action
